mikejohnson51/people-of-ess-330

- csu-ess-330-class.Rproj
- people/Cameron.McLaughlin.csv
> MCLAUGHLIN: Lab 1 Submission

- .gitignore
- people/zachary_cramton.csv
Added Zachary Cramton Lab 1 .csv deliverable.
> CRAMTON: Lab 1 Submission

- people/caitlin_rasbid.csv
> RASBID: Lab 1 Submission

- alex_smilor.csv
This is my Lab 1 Submission for ESS-330
Link to website:
https://alexws23.github.io/
> Alex Smilor: Lab 1 Submission

- people/rinehart_grace.csv.R
> RINEHART: Lab 1 Submission

- people/andie_hall.csv
CSV File under: andie_hall.csv
> Hall,Andie - Lab 1 Submission

- {chloe}_{rogozinski}.csv
> {chloe}_{rogozinski}.csv

- people/Yazeed_Aljohani.csv
Added Yazeed Aljohani to people directory.
> Added Yazeed Aljohani to people directory

- jake_matullo.csv
> MATULLO: Lab 1 Submission

- index.qmd
- people/Austin_Sharrah.csv
I tested gitcommit and gitpush with the index file, but made no changes. I also added Austin_Sharrah csv file in the people folder.
> SHARRAH:Lab_1 Submission

- people/Louisa_Beckett.csv
- people/louisabeckett.csv
> Beckett:Lab 1 Submission

- ChippyMarx.csv
> Marx: Lab 1 Submission

- stephanie_farmer.csv
> FARMER::ab 1 Submission

- people/melissa_may.csv
Submitting my personal webpage
> MAY: Lab 1 Submission

- people/emily_mitchell.csv
Emily Mitchell Lab 1 Submission
> MITCHELL: Lab 1 Submission

- people/Andrew_Zimbelman.csv
This is my submission for lab 1 I really hope it works
> Zimbelman, Lab 1 submission 

- people/Hanna_Velicer.csv
> VELICER: Lab 1 Submission

- sierra_mattair.csv
> Mattair - Lab 1 Submission

- sara_mclaughlin.csv
> Lab 1 submission

- people/nina_hayford.csv
> added nina hayford's csv file

- people/Archer_Goodman.csv
> Goodman: Lab 1 Submission

- people/Noah_Goodhart.csv
Here is my pull request for Lab1
> Goodhart: Lab1 Submission 

- people/kayla_sutton.csv
> SUTTON: Lab 1 submission

- people/sierra_champion.csv
Added my information to the people directory
> Lab 1- Pull Request

- people/megan_hoover.csv
> Hoover: lab 1 submission

- people/sammy_tetrault.csv
Lab 1 pull request to submit csv with website link
> Tetrault: Lab 1 Submission

- Lance_Lowell.csv
Lance Lowell Lab 1 website as well as personal information for the class repository.
> Lowell: Lab 1 Submission

- people/nicholas_beegle
> nicholas_beegle

- people/bailey_stender.csv
> bailey_stender.csv
